import "styles/globals.css"
import CartProvider from "hooks/contexts/useCart"
import ToastProvider from "hooks/contexts/useToast"
import ConfirmationModalProvider from "hooks/contexts/useConfirmationModal"
import AuthProvider from "hooks/contexts/useAuth"
import { ReactNode } from "react"

function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Restaurant</title>
      </head>
      <body>
        <AuthProvider>
          <ToastProvider>
            <CartProvider>
              <ConfirmationModalProvider>{children}</ConfirmationModalProvider>
            </CartProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
